# This file is part of the jebel-quant/rhiza repository
# (https://github.com/jebel-quant/rhiza).
#
# Configuration: GitHub Secret Scanning
#
# Purpose: Configure GitHub secret scanning to identify and prevent accidental
#          exposure of secrets, credentials, and tokens in the repository.
#
# Note: Secret scanning must be enabled in repository Settings >
#       Security > Code security and analysis > Secret scanning.
#
# Documentation: https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repository

paths-ignore:
  # Ignore test fixtures that may contain example/fake secrets
  - ".rhiza/tests/**"
  - "tests/**"
  # Ignore documentation that references example tokens/keys
  - "docs/**/*.md"
  - "book/**"
