template-repository: "tschm/.config-templates"
template-branch: "main"
include: |
    .devcontainer
    .github
    /tests
    .editorconfig
    .pre-commit-config.yaml
    Makefile
exclude: |
  .github/scripts/build-extras.sh
  .github/workflows/docker.yml
