template-repository: "jebel-quant/rhiza"
template-branch: "main"
include:
    - .devcontainer/
    - .github/
    - tests/
    - .editorconfig
    - .pre-commit-config.yaml
    - Makefile
exclude: 
    - .github/scripts/customisations/build-extras.sh
    - .github/workflows/docker.yml
