"""Backward-compatibility tests for the serialized computation format.

Loman promises that a reader accepts every format version from
``MIN_SUPPORTED_VERSION`` up to ``FORMAT_VERSION``.  These tests are what make
that promise enforceable: they read a corpus of files captured at the time each
version was current, so a change that breaks old readers fails CI rather than a
user's post-mortem six months from now.

The corpus lives in ``tests/data/formats/vN/`` and is generated by
``scripts/generate_format_goldens.py``.  Files for a released version must never
be regenerated — that would silently redefine the thing being tested.
"""

from __future__ import annotations

import datetime
import io
import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from loman import Computation, SerializationError, States
from loman.nodekey import to_nodekey
from loman.serialization.computation import (
    FORMAT_VERSION,
    MIN_SUPPORTED_VERSION,
    ComputationSerializer,
)
from tests.format_fixtures import add_one as fx_add_one
from tests.format_fixtures import double as fx_double

GOLDEN_ROOT = Path(__file__).parent / "data" / "formats"


def _golden_files() -> list[Path]:
    """Every golden file across every captured version."""
    return sorted(GOLDEN_ROOT.glob("v*/*.json"))


def _golden_ids(paths: list[Path]) -> list[str]:
    return [f"{p.parent.name}/{p.stem}" for p in paths]


_FILES = _golden_files()


def test_corpus_is_not_empty():
    """A silently empty corpus would make every test below vacuously pass."""
    assert _FILES, f"no golden files found under {GOLDEN_ROOT}"


def test_every_supported_version_has_a_corpus():
    """Each version in the supported range must have golden files."""
    captured = {int(p.name[1:]) for p in GOLDEN_ROOT.iterdir() if p.is_dir() and p.name.startswith("v")}
    expected = set(range(MIN_SUPPORTED_VERSION, FORMAT_VERSION + 1))
    missing = expected - captured
    assert not missing, (
        f"format versions {sorted(missing)} have no golden corpus. "
        f"Run: uv run python scripts/generate_format_goldens.py"
    )


@pytest.mark.parametrize("path", _FILES, ids=_golden_ids(_FILES))
def test_golden_file_reads(path: Path):
    """Every golden file from every supported version still loads."""
    comp = Computation.read_json(str(path))
    assert isinstance(comp, Computation)
    assert len(comp.dag.nodes) > 0


@pytest.mark.parametrize("path", _FILES, ids=_golden_ids(_FILES))
def test_golden_file_version_is_in_range(path: Path):
    """Golden files declare a version this build claims to support."""
    with path.open(encoding="utf-8") as f:
        version = json.load(f)["version"]
    assert MIN_SUPPORTED_VERSION <= version <= FORMAT_VERSION


# ---------------------------------------------------------------------------
# Content assertions — that a file loads is necessary but not sufficient; the
# values have to survive too.
# ---------------------------------------------------------------------------


def _read(version: int, name: str) -> Computation:
    return Computation.read_json(str(GOLDEN_ROOT / f"v{version}" / f"{name}.json"))


def test_v1_scalars_and_funcs():
    """Computed scalar values and their functions round-trip from v1."""
    comp = _read(1, "scalars_and_funcs")
    assert comp.v.a == 3
    assert comp.v.b == 4
    assert comp.v.c == 6
    assert comp.v.d == 10
    # The functions came back as real callables, so the graph can recompute.
    comp.insert("a", 10)
    comp.compute_all()
    assert comp.v.d == 31


def test_v1_all_states():
    """Every state recorded in v1 comes back as itself."""
    comp = _read(1, "all_states")
    assert comp.state("uptodate") == States.UPTODATE
    assert comp.state("pinned") == States.PINNED
    assert comp.state("uninitialized") == States.UNINITIALIZED
    assert comp.state("errored") == States.ERROR
    assert comp.state("computable") == States.COMPUTABLE
    assert comp.state("stale") == States.STALE
    assert comp.v.pinned == 2


def test_v1_error_node_preserves_message():
    """An ERROR node's message survives for post-mortem reading."""
    comp = _read(1, "all_states")
    assert "deliberate golden-file error" in str(comp["errored"].value.exception)


def test_v1_tags_and_exclusions():
    """User tags survive; excluded nodes come back empty but present."""
    comp = _read(1, "tags_and_exclusions")
    assert comp.v.kept == 1
    assert comp.v.plain == "hello"
    assert comp.state("excluded") == States.UNINITIALIZED
    tags = comp.dag.nodes[to_nodekey("kept")]["tag"]
    assert "alpha" in tags
    assert "beta" in tags


def test_v1_numpy_and_pandas():
    """Arrays and frames written by v1 still decode, dtypes included."""
    comp = _read(1, "numpy_and_pandas")
    np.testing.assert_array_equal(comp.v.arr_f8, np.array([1.0, 2.0, 3.0]))
    np.testing.assert_array_equal(comp.v.arr_2d, np.arange(6).reshape(2, 3))
    assert comp.v.arr_f4.dtype == np.float32
    assert comp.v.df.shape == (2, 2)
    assert list(comp.v.df.columns) == ["x", "y"]
    assert comp.v.df["x"].tolist() == [1, 2]
    assert comp.v.series.tolist() == [1, 2, 3]
    assert comp.v.series.name == "s"


def test_v1_containers():
    """Nested lists, tuples and dicts survive."""
    comp = _read(1, "containers")
    assert comp.v.lst == [1, "two", 3.0, None, True]
    assert comp.v.tup == (1, (2, 3), "four")
    assert comp.v.dct == {"a": 1, "b": [2, 3], "c": {"d": 4}}


def test_v1_hierarchical_keys():
    """Block-structured, ``/``-separated node keys survive."""
    comp = _read(1, "hierarchical_keys")
    keys = {str(k) for k in comp.dag.nodes}
    assert "blk/a" in keys
    assert "blk/b" in keys
    assert comp.v["blk/a"] == 7
    assert comp.v["blk/b"] == 8


def test_v2_temporal_columns():
    """Datetime data, which v1 could not encode at all, round-trips from v2."""
    comp = _read(2, "temporal")

    expected = pd.DataFrame({"t": pd.date_range("2024-01-01", periods=3, freq="D")})
    pd.testing.assert_frame_equal(comp.v.dt_col, expected)

    assert pd.isna(comp.v.dt_nat["t"].iloc[1])
    assert str(comp.v.dt_tz["t"].dtype.tz) == "Europe/London"
    assert comp.v.timedelta_col["d"].dtype.kind == "m"
    assert isinstance(comp.v.dt_index.index, pd.DatetimeIndex)
    assert comp.v.dt_array.dtype == np.dtype("datetime64[ns]")


def test_v2_temporal_scalars():
    """Bare temporal scalars keep their exact Python type."""
    comp = _read(2, "temporal")
    assert comp.v.scalar_timestamp == pd.Timestamp("2024-05-05 13:00")
    assert comp.v.scalar_date == datetime.date(2024, 5, 5)
    assert comp.v.scalar_time == datetime.time(13, 30)
    assert comp.v.scalar_timedelta == datetime.timedelta(days=2, hours=3)
    # A stdlib timedelta must not come back as a pandas one.
    assert type(comp.v.scalar_timedelta) is datetime.timedelta


def test_v2_extension_dtypes():
    """Categoricals, nullable ints and MultiIndexes survive with their dtypes."""
    comp = _read(2, "extension_dtypes")

    cat = comp.v.categorical["c"]
    assert isinstance(cat.dtype, pd.CategoricalDtype)
    assert list(cat.cat.categories) == ["b", "a"]
    assert cat.cat.ordered

    assert str(comp.v.nullable["n"].dtype) == "Int64"
    assert comp.v.nullable["n"].isna().tolist() == [False, True, False]

    assert isinstance(comp.v.multiindex.index, pd.MultiIndex)
    assert list(comp.v.multiindex.index.names) == ["k", "n"]

    # Per-column dtypes are preserved rather than collapsed through object.
    # Compared against a freshly built frame rather than hardcoded names, since
    # pandas 2 and 3 disagree about the default dtype for a string column.
    native = pd.DataFrame({"i": [1, 2], "f": [1.5, 2.5], "s": ["a", "b"], "b": [True, False]})
    assert list(comp.v.mixed.dtypes) == list(native.dtypes)

    assert comp.v.str_array.dtype.kind == "U"


def test_v2_columnwise_encoding_is_actually_used():
    """Guard against silently falling back to the v1 whole-frame encoding."""
    with (GOLDEN_ROOT / "v2" / "extension_dtypes.json").open(encoding="utf-8") as f:
        data = json.load(f)
    mixed = next(n for n in data["nodes"] if n["key"] == "mixed")
    assert "cols" in mixed["value"], "expected the column-wise encoding"
    assert "data" not in mixed["value"], "v1 whole-frame encoding leaked into v2"


# ---------------------------------------------------------------------------
# Version negotiation
# ---------------------------------------------------------------------------


def test_future_version_is_rejected_with_an_actionable_message():
    """A document from a newer loman fails loudly rather than half-parsing."""
    doc = {"version": FORMAT_VERSION + 1, "nodes": [], "edges": []}
    with pytest.raises(SerializationError) as exc:
        Computation.read_json(io.StringIO(json.dumps(doc)))
    msg = str(exc.value)
    assert str(FORMAT_VERSION + 1) in msg
    assert "Upgrade loman" in msg


def test_missing_version_is_rejected():
    """A document with no version field cannot be identified, so it is refused."""
    doc = {"nodes": [], "edges": []}
    with pytest.raises(SerializationError, match="no 'version' field"):
        Computation.read_json(io.StringIO(json.dumps(doc)))


def test_non_integer_version_is_rejected():
    """A version that is not an integer is a malformed document."""
    doc = {"version": "2", "nodes": [], "edges": []}
    with pytest.raises(SerializationError, match="non-integer format version"):
        Computation.read_json(io.StringIO(json.dumps(doc)))


def test_boolean_version_is_rejected():
    """``True`` is an int in Python; it is still not a version number."""
    doc = {"version": True, "nodes": [], "edges": []}
    with pytest.raises(SerializationError, match="non-integer format version"):
        Computation.read_json(io.StringIO(json.dumps(doc)))


def test_too_old_version_is_rejected(monkeypatch):
    """A version below the supported floor is refused, not guessed at."""
    monkeypatch.setattr("loman.serialization.computation.MIN_SUPPORTED_VERSION", 2)
    doc = {"version": 1, "nodes": [], "edges": []}
    with pytest.raises(SerializationError, match="no longer reads"):
        Computation.read_json(io.StringIO(json.dumps(doc)))


def test_current_version_is_written():
    """Fresh documents carry the current format version."""
    comp = Computation()
    comp.add_node("a", value=1)
    data = json.loads(ComputationSerializer().dumps(comp))
    assert data["version"] == FORMAT_VERSION


# ---------------------------------------------------------------------------
# Partial reads
# ---------------------------------------------------------------------------


def test_read_json_with_nodes_materialises_only_those_nodes():
    """Unrequested nodes keep their wiring but drop their values."""
    comp = Computation()
    comp.add_node("a", value=1)
    comp.add_node("b", value=pd.DataFrame({"x": [1, 2]}))
    comp.add_node("c", value="kept")
    buf = io.StringIO()
    comp.write_json(buf)
    buf.seek(0)

    got = Computation.read_json(buf, nodes=["a", "c"])
    assert got.v.a == 1
    assert got.v.c == "kept"
    assert got.state("b") == States.UNINITIALIZED
    # The node itself is still there — only its payload was skipped.
    assert "b" in {str(k) for k in got.dag.nodes}


def test_partial_read_keeps_graph_shape():
    """Edges survive a partial read, so the graph is still recomputable."""
    comp = Computation()
    comp.add_node("a", value=3)
    comp.add_node("b", lambda a: a + 1)
    comp.compute_all()
    s = ComputationSerializer(use_dill_for_functions=True)
    buf = io.StringIO()
    comp.write_json(buf, serializer=s)
    buf.seek(0)

    got = Computation.read_json(buf, serializer=s, nodes=["a"])
    assert got.v.a == 3
    # 'b' was skipped, but it has a function and its input is loaded, so it is
    # computable rather than uninitialized — the graph can just be recomputed.
    assert got.state("b") == States.COMPUTABLE
    got.compute_all()
    assert got.v.b == 4


def test_partial_read_settles_a_chain_of_skipped_nodes():
    """Skipped nodes resolve in topological order, not just one level deep."""
    comp = Computation()
    comp.add_node("a", value=3)
    comp.add_node("b", fx_add_one, kwds={"x": "a"})
    comp.add_node("c", fx_double, kwds={"x": "b"})
    comp.compute_all()
    buf = io.StringIO()
    comp.write_json(buf)
    buf.seek(0)

    got = Computation.read_json(buf, nodes=["a"])
    assert got.state("b") == States.COMPUTABLE
    # 'c' cannot be computable yet — its own input is not loaded.
    assert got.state("c") == States.UNINITIALIZED
    got.compute_all()
    assert got.v.c == 8
