## .rhiza/make.d/tutorial.mk - Interactive Tutorial

.PHONY: tutorial

##@ Learning and Onboarding
tutorial: ## interactive tutorial with guided walkthrough of key features
	@printf "${BLUE}"
	@printf "╔════════════════════════════════════════════════════════════════════════════╗\n"
	@printf "║                   Welcome to the Rhiza Interactive Tutorial!              ║\n"
	@printf "║                                                                            ║\n"
	@printf "║  This tutorial will guide you through the key features of Rhiza.          ║\n"
	@printf "║  Follow along and try the commands as we go!                              ║\n"
	@printf "╚════════════════════════════════════════════════════════════════════════════╝\n"
	@printf "${RESET}\n"
	@sleep 2
	@printf "${BOLD}📚 Lesson 1: Understanding Rhiza${RESET}\n"
	@printf "Rhiza is a living template system for Python projects.\n"
	@printf "Unlike traditional templates, Rhiza keeps your project synchronized\n"
	@printf "with best practices through continuous updates.\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🔧 Lesson 2: Essential Commands${RESET}\n"
	@printf "Let's explore the most important make targets:\n\n"
	@printf "${GREEN}  make help${RESET}        - Show all available commands\n"
	@printf "${GREEN}  make install${RESET}     - Install dependencies and set up environment\n"
	@printf "${GREEN}  make test${RESET}        - Run all tests with coverage\n"
	@printf "${GREEN}  make fmt${RESET}         - Format and lint your code\n\n"
	@printf "${YELLOW}Try running '${GREEN}make help${YELLOW}' now to see all commands.${RESET}\n"
	@printf "${YELLOW}Press Enter when done...${RESET}\n" && read -r
	@printf "\n${BOLD}🏗️ Lesson 3: Project Structure${RESET}\n"
	@printf "Key directories in a Rhiza project:\n\n"
	@printf "${GREEN}.rhiza/${RESET}          - Template-managed files (do not edit directly)\n"
	@printf "${GREEN}.rhiza/make.d/${RESET}   - Modular Makefile components (auto-loaded)\n"
	@printf "${GREEN}Makefile${RESET}         - Your project-specific customizations\n"
	@printf "${GREEN}local.mk${RESET}         - Developer-local overrides (not committed)\n"
	@printf "${GREEN}pyproject.toml${RESET}   - Python project configuration\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🔄 Lesson 4: Template Synchronization${RESET}\n"
	@printf "Rhiza keeps your project up-to-date with template changes:\n\n"
	@printf "${GREEN}  make sync${RESET}           - Sync with upstream template\n"
	@printf "${GREEN}  make summarise-sync${RESET} - Preview sync changes without applying\n"
	@printf "${GREEN}  make validate${RESET}       - Validate project structure\n\n"
	@printf "Configuration is in ${GREEN}.rhiza/template.yml${RESET}\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🎨 Lesson 5: Customization${RESET}\n"
	@printf "You can extend Rhiza without breaking template sync:\n\n"
	@printf "1. ${BOLD}Add custom targets${RESET} in your root Makefile:\n"
	@printf "   ${GREEN}my-task: ## Description\n"
	@printf "   	@echo 'Custom task'${RESET}\n\n"
	@printf "2. ${BOLD}Use hooks${RESET} to inject logic into standard workflows:\n"
	@printf "   ${GREEN}post-install::\n"
	@printf "   	@echo 'Additional setup'${RESET}\n\n"
	@printf "3. ${BOLD}Create local overrides${RESET} in local.mk (not committed)\n\n"
	@printf "${YELLOW}See docs/CUSTOMIZATION.md and docs/EXTENDING_RHIZA.md for details.${RESET}\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🧪 Lesson 6: Development Workflow${RESET}\n"
	@printf "Typical development cycle:\n\n"
	@printf "1. ${GREEN}make install${RESET}     - Set up your environment (first time)\n"
	@printf "2. ${GREEN}# Write code...${RESET}\n"
	@printf "3. ${GREEN}make test${RESET}        - Run tests to verify changes\n"
	@printf "4. ${GREEN}make fmt${RESET}         - Format code before committing\n"
	@printf "5. ${GREEN}git commit${RESET}       - Commit your changes\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}📦 Lesson 7: Dependency Management${RESET}\n"
	@printf "Rhiza uses uv for fast, reliable dependency management:\n\n"
	@printf "${GREEN}  uv add package-name${RESET}    - Add a new dependency\n"
	@printf "${GREEN}  uv remove package-name${RESET} - Remove a dependency\n"
	@printf "${GREEN}  uv sync${RESET}                - Sync dependencies with lock file\n"
	@printf "${GREEN}  uv run python${RESET}          - Run Python in virtual environment\n"
	@printf "${GREEN}  uv run pytest${RESET}          - Run pytest\n\n"
	@printf "${YELLOW}Never call .venv/bin/python directly - always use 'uv run'!${RESET}\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🚀 Lesson 8: Releasing${RESET}\n"
	@printf "Streamlined version management and releases:\n\n"
	@printf "${GREEN}  make publish${RESET}      - Bump version, create tag, and push (all-in-one)\n"
	@printf "${GREEN}  make bump${RESET}         - Bump version (prompts for major/minor/patch)\n"
	@printf "${GREEN}  make release${RESET}      - Create and push release tag\n"
	@printf "${GREEN}  make release-status${RESET} - Show release workflow status\n\n"
	@printf "Version is in ${GREEN}pyproject.toml${RESET} and tags are prefixed with 'v'\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}📚 Lesson 9: Documentation${RESET}\n"
	@printf "Generate and view documentation:\n\n"
	@printf "${GREEN}  make docs${RESET}         - Generate API documentation with pdoc\n"
	@printf "${GREEN}  make book${RESET}         - Build companion book\n"
	@printf "${GREEN}  make mkdocs-serve${RESET} - Serve MkDocs site with live reload\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}🤖 Lesson 10: AI-Powered Workflows${RESET}\n"
	@printf "Rhiza includes AI-assisted development tools:\n\n"
	@printf "${GREEN}  make copilot${RESET}          - Open GitHub Copilot CLI\n"
	@printf "${GREEN}  make claude${RESET}           - Open Claude Code interactive prompt\n"
	@printf "${GREEN}  make analyse-repo${RESET}     - AI analysis of repository structure\n"
	@printf "${GREEN}  make summarise-changes${RESET} - Summarize changes since last release\n\n"
	@printf "${YELLOW}Press Enter to continue...${RESET}\n" && read -r
	@printf "\n${BOLD}✨ Tutorial Complete!${RESET}\n\n"
	@printf "You've learned the essentials of working with Rhiza.\n\n"
	@printf "${BOLD}Next steps:${RESET}\n"
	@printf "  • Read ${GREEN}docs/TOOLS_REFERENCE.md${RESET} for command quick reference\n"
	@printf "  • Read ${GREEN}docs/EXTENDING_RHIZA.md${RESET} for customization patterns\n"
	@printf "  • Read ${GREEN}docs/CUSTOMIZATION.md${RESET} for advanced topics\n"
	@printf "  • Try ${GREEN}make help${RESET} to see all available commands\n"
	@printf "  • Check ${GREEN}README.md${RESET} for project-specific information\n\n"
	@printf "${BLUE}Happy coding with Rhiza! 🌱${RESET}\n\n"
