template-repository: "jebel-quant/rhiza"
template-branch: "main"
include:
    - .devcontainer/
    - .github/
    - tests/
    - .editorconfig
    - .pre-commit-config.yaml
    - Makefile
    - presentation
    - book/Makefile.book
exclude: 
    - .github/rhiza/scripts/customisations/build-extras.sh
    - .github/workflows/rhiza_docker.yml
    - .github/rhiza/CONFIG.md
    - .github/rhiza/TOKEN_SETUP.md
