# This file is part of the jebel-quant/rhiza repository
# (https://github.com/jebel-quant/rhiza).
#
# Action: Setup Project (composite action)
#
# Purpose: Bootstrap a Python project in GitHub Actions by:
#   - Installing Task, uv, and uvx
#   - Detecting presence of pyproject.toml and exposing it as an output
#   - Creating a virtual environment with uv and syncing dependencies
#
# Inputs:
#   - python-version: Python version used for the virtual environment (default: 3.12)
#     Can be overridden by setting PYTHON_DEFAULT_VERSION repository variable
#   - uv-extra-index-url: Extra index URL for uv (optional)
#
# Notes:
#   - Used by workflows such as CI, Book, Marimo, and Release.

name: 'Setup Project'
description: 'Setup the project'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-extra-index-url:
    description: 'Extra index URL for uv'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.18"

    - name: Build the virtual environment
      shell: bash
      run: uv venv --python ${{ inputs.python-version }}

    - name: "Sync the virtual environment for ${{ github.repository }}"
      shell: bash
      run: |
        if [[ -n "${{ inputs.uv-extra-index-url }}" ]]; then
          export UV_EXTRA_INDEX_URL="${{ inputs.uv-extra-index-url }}"
        fi

        uv sync --all-extras --frozen
